//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            salida = new HashSet<salida>();
            licencias = new HashSet<licencias>();
            permisos = new HashSet<permisos>();
            vacaciones = new HashSet<vacaciones>();
        }
        public int id_empleado { get; set; }
        public string codigo_empleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string departamento { get; set; }
        public string cargo { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<decimal> salario { get; set; }
        public string estatus { get; set; }
        
         
        public virtual cargo cargo1 { get; set; }
        public virtual departamento departamento1 { get; set; }
        public virtual licencias licencias { get; set; }
        public virtual permisos permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salida> salida { get; set; }
        public virtual vacaciones vacaciones { get; set; }
    }
}
