//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class GestionRecursosHumanosEntities : DbContext
    {
        public GestionRecursosHumanosEntities()
            : base("name=GestionRecursosHumanosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<licencias> licencias { get; set; }
        public virtual DbSet<nomina> nomina { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<salida> salida { get; set; }
        public virtual DbSet<vacaciones> vacaciones { get; set; }
    }
}
