//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida
    {
        public int id_salida { get; set; }
        public string empleado { get; set; }
        public string tiposalida { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fechasalida { get; set; }
    
        public virtual empleado empleado1 { get; set; }
    }
}
